[package]
name = "sync_player"
version = "0.1.0"
edition = "2021"
default-run = "sync_player"

[[bin]]
name = "sync_player_server"
path = "src/server.rs"


[dependencies]
confy = "0.6.1"
dns-lookup = "2.0.4"
libmpv-sirno = "2.0.2-fork.1"
serde = { version = "1.0.197", features = ["derive"] }

